/** Public Firebase Storage URLs — generated by `npm run upload:assets`. Do not edit by hand. */

export const FIREBASE_STORAGE_BUCKET = 'monstarx-templates.firebasestorage.app';

export const FIREBASE_VEHICLE_IMAGES: Record<string, string> = {
  'veh-1': 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/vehicles/veh-1.jpg',
  'veh-2': 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/vehicles/veh-2.jpg',
  'veh-3': 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/vehicles/veh-3.svg',
  'veh-4': 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/vehicles/veh-4.jpg',
  'veh-5': 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/vehicles/veh-5.jpg',
  'veh-6': 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/vehicles/veh-6.jpg',
  'veh-7': 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/vehicles/veh-7.svg',
  'veh-8': 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/vehicles/veh-8.jpg',
};

export const FIREBASE_MARKETING_HERO = 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/marketing/hero.jpg';
export const FIREBASE_LOGIN_HERO = 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/login/hero.jpg';
export const FIREBASE_FAVICON = 'https://storage.googleapis.com/monstarx-templates.firebasestorage.app/drivexpro/branding/favicon.svg';
